from enum import Enum

class GrowwVerdict(str, Enum):
    TOP_BUY = "TOP_BUY"
    BUY = "BUY"
    HOLD = "HOLD"
    SELL = "SELL"


class AssetCategory(str, Enum):
    EQUITY = "Equity"
    DEBT = "Debt"
    HYBRID = "Hybrid"
    COMMODITIES = "Commodities"


class SubCategory(str, Enum):
    # Equity
    FLEXI_CAP = "Flexi Cap"
    INTERNATIONAL = "International"
    LARGE_AND_MIDCAP = "Large & MidCap"
    LARGE_CAP = "Large Cap"
    MID_CAP = "Mid Cap"
    MULTI_CAP = "Multi Cap"
    SECTORAL = "Sectoral"
    SMALL_CAP = "Small Cap"
    ELSS = "ELSS"
    THEMATIC = "Thematic"
    VALUE_ORIENTED = "Value Oriented"
    
    # Debt
    BANKING_AND_PSU = "Banking and PSU"
    CORPORATE_BOND = "Corporate Bond"
    CREDIT_RISK = "Credit Risk"
    DYNAMIC_BOND = "Dynamic Bond"
    FIXED_MATURITY = "Fixed Maturity"
    FLOATER = "Floater"
    GILT = "Gilt"
    GILT_10Y_CONSTANT = "Gilt with 10 year Constant Duration"
    LIQUID = "Liquid"
    LONG_DURATION = "Long Duration"
    LOW_DURATION = "Low Duration"
    MEDIUM_DURATION = "Medium Duration"
    MEDIUM_TO_LONG_DURATION = "Medium to Long Duration"
    MONEY_MARKET = "Money Market"
    OVERNIGHT = "Overnight"
    SHORT_DURATION = "Short Duration"
    TARGET_MATURITY = "Target Maturity"
    ULTRA_SHORT_DURATION = "Ultra Short Duration"
    
    # Hybrid
    AGGRESSIVE_HYBRID = "Aggressive Hybrid"
    ARBITRAGE = "Arbitrage"
    BALANCED_HYBRID = "Balanced Hybrid"
    CONSERVATIVE_HYBRID = "Conservative Hybrid"
    DYNAMIC_ASSET_ALLOCATION = "Dynamic Asset Allocation"
    EQUITY_SAVINGS = "Equity Savings"
    MULTI_ASSET_ALLOCATION = "Multi Asset Allocation"
    
    # Commodities
    GOLD = "Gold"
    SILVER = "Silver"


class SortOption(str, Enum):
    POPULARITY = "3"
    PRIME_VERDICT = "10"
    RETURNS_1Y = "4"
    RETURNS_3Y = "0"
    RETURNS_5Y = "5"


class RiskLevel(str, Enum):
    LOW = "Low"
    MODERATELY_LOW = "Moderately Low"
    MODERATE = "Moderate"
    MODERATELY_HIGH = "Moderately High"
    HIGH = "High"
    VERY_HIGH = "Very High"


class FundHouse(str, Enum):
    THREE_SIXTY_ONE = "360 ONE Mutual Fund"
    ABAKKUS = "Abakkus Mutual Fund"
    ADITYA_BIRLA_SUN_LIFE = "Aditya Birla Sun Life Mutual Fund"
    ANGEL_ONE = "Angel One Mutual Fund"
    AXIS = "Axis Mutual Fund"
    BAJAJ_FINSERV = "Bajaj Finserv Mutual Fund"
    BANDHAN = "Bandhan Mutual Fund"
    BANK_OF_INDIA = "Bank of India Mutual Fund"
    BARODA_BNP_PARIBAS = "Baroda BNP Paribas Mutual Fund"
    BARODA = "Baroda Mutual Fund"
    BNP_PARIBAS = "BNP Paribas Mutual Fund"
    CANARA_ROBECO = "Canara Robeco Mutual Fund"
    CAPITALMIND = "Capitalmind Mutual Fund"
    DHFL_PRAMERICA = "DHFL Pramerica Mutual Fund"
    DSP = "DSP Mutual Fund"
    EDELWEISS = "Edelweiss Mutual Fund"
    FRANKLIN_TEMPLETON = "Franklin Templeton Mutual Fund"
    GROWW = "Groww Mutual Fund"
    HDFC = "HDFC Mutual Fund"
    HELIOS = "Helios Mutual Fund"
    HSBC = "HSBC Mutual Fund"
    ICICI_PRUDENTIAL = "ICICI Prudential Mutual Fund"
    IDFC = "IDFC Mutual Fund"
    IIFL = "IIFL Mutual Fund"
    INVESCO = "Invesco Mutual Fund"
    ITI = "ITI Mutual Fund"
    JM_FINANCIAL = "JM Financial Mutual Fund"
    KOTAK_MAHINDRA = "Kotak Mahindra Mutual Fund"
    L_AND_T = "L&T Mutual Fund"
    LIC = "LIC Mutual Fund"
    MAHINDRA_MANULIFE = "Mahindra Manulife Mutual Fund"
    MAHINDRA = "Mahindra Mutual Fund"
    MIRAE_ASSET = "Mirae Asset Mutual Fund"
    MOTILAL_OSWAL = "Motilal Oswal Mutual Fund"
    NAVI = "Navi Mutual Fund"
    NIPPON_INDIA = "Nippon India Mutual Fund"
    NJ = "NJ Mutual Fund"
    OLD_BRIDGE = "Old Bridge Mutual Fund"
    PGIM_INDIA = "PGIM India Mutual Fund"
    PPFAS = "PPFAS Mutual Fund"
    QUANT = "Quant Mutual Fund"
    QUANTUM = "Quantum Mutual Fund"
    RELIANCE = "Reliance Mutual Fund"
    SAMCO = "Samco Mutual Fund"
    SBI = "SBI Mutual Fund"
    SHRIRAM = "Shriram Mutual Fund"
    SUNDARAM = "Sundaram Mutual Fund"
    TATA = "Tata Mutual Fund"
    TAURUS = "Taurus Mutual Fund"
    THE_WEALTH_COMPANY = "The Wealth Company Mutual Fund"
    TRUST = "Trust Mutual Fund"
    UNIFI = "Unifi Mutual Fund"
    UNION = "Union Mutual Fund"
    UTI = "UTI Mutual Fund"
    WHITEOAK_CAPITAL = "WhiteOak Capital Mutual Fund"
    YES = "YES Mutual Fund"
